### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by EmperorArthur** [etherboot/gpxe#2]
This is me not realizing this is a historic archive for a program which changed names to [iPXE](https://ipxe.org/).

I blame the [Wiki](http://etherboot.org/wiki/start).

**Comment by FlorentFlament** [comment]
Hi,

This repo actually does compile on a 32 bits system with gcc 4.x. I added a Vagrantfile that spawns such a VM to my gPXE fork (https://github.com/FlorentFlament/gpxe), and documented how to build the images. Also I published the images of gPXE v1.0.1 (https://github.com/FlorentFlament/gpxe/releases/tag/v1.0.1).

I hope this helps.
Happy hacking

**Comment by EmperorArthur** [comment]
Thank you for your help.  I moved to iPXE and all of the compilation issues were resolved.

**Comment by FlorentFlament** [comment]
Nice, I didn't know about this iPXE project. That would have avoided me the hassle of compiling gPXE ; ) I think I'll give it a try. Thanks for the info !
